import { z } from 'zod';

/**
 * Output schemas for the travel agent.
 *
 * These define the TripRecommendation contract every provider (mock or real LLM) must
 * satisfy. The pipeline validates provider output against these schemas, so a model that
 * hallucinates an off-shape response is caught server-side instead of reaching the UI.
 */

/**
 * A single cost line item. `confidence` makes the estimate-vs-confirmed distinction
 * explicit and machine-readable so the UI can label prices honestly.
 */
export const CostItemSchema = z.object({
  label: z.string().min(1),
  amountUsd: z.number().min(0),
  // 'estimate'  -> model's best guess, show with an "est." qualifier
  // 'confirmed' -> a real, looked-up price (reserved for future price integrations)
  confidence: z.enum(['estimate', 'confirmed']).default('estimate'),
});

export const ActivitySchema = z.object({
  time: z.string().min(1), // e.g. "09:00" or "Morning"
  title: z.string().min(1),
  description: z.string().default(''),
  // Rough travel time to reach this activity from the previous one, in minutes.
  travelFromPreviousMin: z.number().min(0).default(0),
  estimatedCostUsd: z.number().min(0).default(0),
});

export const ItineraryDaySchema = z.object({
  day: z.number().int().min(1),
  title: z.string().min(1),
  summary: z.string().default(''),
  activities: z.array(ActivitySchema).min(1),
});

/**
 * A candidate destination the agent considered, with the reasoning the user asked for:
 * why it fits, its distance, and an estimated cost.
 */
export const DestinationSchema = z.object({
  name: z.string().min(1),
  country: z.string().default(''),
  distanceKm: z.number().min(0),
  // Human-readable justification tying the destination to the user's interests/budget.
  whyItFits: z.string().min(1),
  estimatedTotalCostUsd: z.number().min(0),
  matchedInterests: z.array(z.string()).default([]),
});

/**
 * The full recommendation returned to the client.
 */
export const TripRecommendationSchema = z.object({
  title: z.string().min(1),
  summary: z.string().min(1),

  // The destination the itinerary is built around, plus the runners-up the agent weighed.
  destination: DestinationSchema,
  consideredDestinations: z.array(DestinationSchema).default([]),

  itinerary: z.array(ItineraryDaySchema).min(1),

  // Structured budget breakdown. `withinBudget` is set by the budget-validation stage,
  // not by the model, so it reflects a server-side check.
  budget: z.object({
    currency: z.literal('USD').default('USD'),
    limitUsd: z.number().min(0),
    estimatedTotalUsd: z.number().min(0),
    withinBudget: z.boolean(),
    breakdown: z.array(CostItemSchema).default([]),
  }),

  // Honesty note shown in the UI: these are estimates, not bookable prices.
  disclaimer: z
    .string()
    .default(
      'All prices are estimates generated by an AI assistant, not confirmed bookings. ' +
        'Verify costs and availability before booking.',
    ),

  // Provenance so callers can see which provider produced this (UI stays agnostic).
  meta: z
    .object({
      provider: z.string(),
      model: z.string().optional(),
      generatedAt: z.string(),
    })
    .optional(),
});

/** @typedef {z.infer<typeof TripRecommendationSchema>} TripRecommendation */
